// Original Code by MrPowerGamerBR and the Butterscotch contributors.
// Modifications Copyright (c) 2026 Efim Andreev and Vyacheslav Ivanov.
//
// This file is part of Butterscotch (Nintendo 3DS port).
//
// Butterscotch is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, version 3.

#pragma once

#include <common.h>
#include <stdint.h>
#include <stddef.h>

// Decodes a texture blob (PNG, GameMaker custom QOI, or BZip2+QOI) into RGBA8 pixel data.
// "gm2022_5" should be set when it is a QOI image generated by GameMaker 2022.5+, because it includes the uncompressed length in the header.
// Returns a malloc'd buffer of size (*outW) * (*outH) * 4 bytes, or nullptr on failure.
// Caller is responsible for passing the returned buffer to ImageDecoder_freeRgba().
uint8_t* ImageDecoder_decodeToRgba(const uint8_t* blob, size_t blobSize, bool gm2022_5, int* outW, int* outH);

void ImageDecoder_freeRgba(uint8_t* pixels);
